Initial set up and Add Assessment form
cul-2016/study-planner pull request #11
Opened 2018-08-08 10:28 UTC by Danwhy

* adds initial set up for the app,
* adds routing,
* adds form for students adding assessment

ref #2

2018-08-08 19:23 UTC, iteles requested changes
@Danwhy Could we please add a bit more to the readme so we have an explanation of what's happening and why it's in a separate repo with our first merge?

2018-08-09 16:16 UTC, iteles approved these changes
Good enough so we don't just have a blank readme 👍 Approving to remove my 'request changes' from before

2018-08-09 16:17 UTC, Danwhy commented
:+1: I'll update it as more features get added

2018-08-10 08:13 UTC, sohilpandya commented
Probably worth adding a `.nvmrc` file in with the version of node that we are using. So that we all have the same deps.

2018-08-10 08:20 UTC, sohilpandya requested changes
Hey! looking good, just a couple of things on here.

2018-08-10 08:20 UTC, sohilpandya commented on src/AddAssessment.js
> +          {["Very Low", "Low", "Medium", "High", "Very High"].map((v, i) => {
Is this going to be a set list? Likely move this and line 45 out and create const for them and then use that in here. 

makes it slightly more readable.

2018-08-10 08:21 UTC, sohilpandya commented
Also @Danwhy, I am unable to change labels etc in here. could you please add me to the team on here :)

2018-08-10 23:35 UTC, sohilpandya approved these changes

2018-08-10 23:35 UTC, sohilpandya commented
LGTM 👍

2018-08-10 23:35 UTC, merged