Display targets
cul-2016/study-planner pull request #12
Opened 2018-08-08 10:30 UTC by Danwhy

Basic display of each assessment added

ref #5

2018-08-11 07:43 UTC, sohilpandya requested changes
I'm not sure if I was suppose to review this. But I've added some comments on here. 

Couple of additional notes:
- probably worth thinking about folder structure now that we are adding a few more files.
- Are we using tachyons? We should ideally require just one CSS file at the index level, but we can talk about this once we've deicided what route we are taking with CSS :)

2018-08-11 07:43 UTC, sohilpandya commented on src/App.js
> +  addAssessment(assessment) {
I would utilise the new arrow functions here so that we don't need to pass context around for `this` 

`addAssessment = (assessment) => { `

2018-08-11 07:43 UTC, sohilpandya commented on src/App.js
> +          <Route path="/add-assessment" render={(props) => <AddAssessment {...props} addAssessment={this.addAssessment.bind(this)}/>}/>
Now, this doesn't need to bind. It can just be `this.addAssessment`

2018-08-11 07:43 UTC, sohilpandya commented on src/AddAssessment.js
> +  addAssessment () {
apply the same idea and turn this into an arrow function. `addAssessment = () => {`

2018-08-11 07:43 UTC, sohilpandya commented on src/AddAssessment.js
> +        <button onClick={this.addAssessment.bind(this)}>Add Assessment</button>
The onClick can be `{() => this.addAssessment()} `

2018-08-11 07:43 UTC, sohilpandya commented on src/AddAssessment.js
> +            return <RadioButton value={(i+1).toString()} key={i}>{v}</RadioButton>
We could use string interpolation here instead of toString

2018-08-11 07:43 UTC, sohilpandya commented on src/List.js
> +        <button onClick={this.props.history.goBack}>{"<- Back"}</button>
What's the desired behaviour here? At the moment, if you add an item then you are redirected here. If you click back then you are taken to the addassessment screen. 

Probably want to have a hard coded link to take us back to the home page instead?

2018-08-13 10:32 UTC, Danwhy commented
Thanks @sohilpandya, I'll tidy up the folder structure in the next PR. I'm not sure yet whether I'm going to be using tachyons or if I'll reuse some styling from the main Quodl app, but the current css is very much just a placeholder

2018-08-13 19:02 UTC, sohilpandya approved these changes

2018-08-13 19:03 UTC, merged

2018-08-13 19:03 UTC, sohilpandya commented
👍